INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Binary Family History Blanket', '{"tags":["blanket","binary","animals","geometric"]}', 'https://pbs.twimg.com/profile_images/878962163737665537/OLAUQNQe_400x400.jpg', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'blanket', 12.99, null, 0);
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Parents and Kids Family History Blanket', '{"tags":["blanket","inverted","family","geometric","geneaology"]}', 'https://images.unsplash.com/photo-1540844775339-de8c67e13da4?ixlib=rb-0.3.5&s=fc4fae50596e7b8bea134cc641acea2c&auto=format&fit=crop&w=400&q=80', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'blanket', 12.99, null, 0);
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping, o1)
VALUES ('Personalized Missionary Journal', '{"tags":["journal","missionary","state","alabama"]}', 'https://images.unsplash.com/photo-1540889539617-6236fa68e2f0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=64923c5e7a9e7b435b9058949a2cb5d8&auto=format&fit=crop&w=400&q=80', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'journal', 12.99, null, 3.99, '["title","subtitle","date"]');
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Bear Baby Blanket', '{"tags":["blanket","baby","animals","geometric"]}', 'https://images.unsplash.com/photo-1540845692348-b9d2bc813a63?ixlib=rb-0.3.5&s=b0c0bbbebc81382380cd4b826ba5083d&auto=format&fit=crop&w=400&q=80', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'blanket', 12.99, null, 0);
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping, o1)
VALUES ('EveryDay Journal Mountains', '{"tags":["journal","animal","nature","scenic"]}', 'https://images.unsplash.com/photo-1540877644327-477011fe0afd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6e288ba6f8f31ef9b859f41ef9a5d9b7&auto=format&fit=crop&w=400&q=80', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'journal', 12.99, null, 3.99, '["title","subtitle"]');
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping, o1)
VALUES ('EveryDay Journal Mountains', '{"tags":["journal","animal","nature","scenic"]}', 'https://images.unsplash.com/photo-1540877644327-477011fe0afd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6e288ba6f8f31ef9b859f41ef9a5d9b7&auto=format&fit=crop&w=400&q=80', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'journal', 12.99, null, 3.99, '["title","subtitle","date"]');
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping, o1)
VALUES ('EveryDay Journal Mountains', '{"tags":["journal","animal","nature","scenic"]}', 'https://images.unsplash.com/photo-1540877644327-477011fe0afd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6e288ba6f8f31ef9b859f41ef9a5d9b7&auto=format&fit=crop&w=400&q=80', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'journal', 12.99, null, 3.99, '["title","subtitle","date"]');
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping, o1)
VALUES ('EveryDay Journal Mountains', '{"tags":["blanket","single","nature","scenic"]}', 'https://images.unsplash.com/photo-1540877644327-477011fe0afd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6e288ba6f8f31ef9b859f41ef9a5d9b7&auto=format&fit=crop&w=400&q=80', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'journal', 12.99, null, 3.99, '["title","subtitle","date"]');
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping, o1)
VALUES ('Cold Outside Holiday Blanket', '{"tags":["blanket","holiday","snow","cute"]}', 'https://images.unsplash.com/photo-1418662589339-364ad47f98a2?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=235f484b2cdafba4d0e2fa382f09286f&auto=format&fit=crop&w=400&q=80', '{"thumbnails":["http://image.jpg","http://image.jpg"]}', 'ultra fuzzy soft lorem ipsum blanket waifu...', 'blanket', 12.99, null, 0, '["title","subtitle","date"]');



INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Singles Family History Blanket',
 '{"tags":["blanket","single","tree","family", "history", "genealogy", "custom", "branches", "soft", "fuzzy", "minky", "personal","grandkids","grandchildren","grandparents","children","parents"]}',
  'https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3Gen_Gray_Fall_Front.jpg',
	 '{"thumbnails":["https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3Gen_Gray_Fall_Back.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/1_Dark_Brown_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/2_Gray_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3_Beige_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/4_Olive_Green_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/5_Gold_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/6_Blue_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/7_Beige_Summer_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/8_Minky_Texture.jpg"]}',
	  'insert product description here',
		 'blanket_single', 169.99, 129.99, 0);
		 
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Couples Family History Blanket',
 '{"tags":["blanket","binary","tree","family", "history", "genealogy", "custom", "branches", "soft", "fuzzy", "minky", "personal","couple","pair","married","spouse","grandkids","grandchildren","grandparents","children","parents"]}',
  'https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3Gen_Gray_Fall_Front.jpg',
	 '{"thumbnails":["https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3Gen_Gray_Fall_Back.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/1_Dark_Brown_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/2_Gray_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3_Beige_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/4_Olive_Green_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/5_Gold_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/6_Blue_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/7_Beige_Summer_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/8_Minky_Texture.jpg"]}',
	  'insert product description here',
		 'blanket_binary', 169.99, 129.99, 0);

INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Grandparents, Kids and Grandkids Family History Blanket',
 '{"tags":["blanket","inverted","tree","family", "history", "genealogy", "custom", "branches", "soft", "fuzzy", "minky", "personal","kids","progeny","grandkids","grandchildren","grandparents","children","parents"]}',
  'https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/GKG_Front_Photo.jpg',
	 '{"thumbnails":["https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/GKG_Back_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/1_Dark_Brown_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/2_Gray_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/3_Beige_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/4_Olive_Green_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/5_Gold_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/6_Blue_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/7_Beige_Summer_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/8_Minky_Texture.jpg"]}',
	  'insert product description here',
		 'blanket_inverted', 169.99, 129.99, 0);

INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Singles Family History Print',
 '{"tags":["blanket","printsingle","tree","family", "history", "genealogy", "custom", "branches","personal","grandkids","grandchildren","grandparents","children","parents"]}',
  'https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3Gen_Gray_Fall_Front.jpg',
	 '{"thumbnails":["https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3Gen_Gray_Fall_Back.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/1_Dark_Brown_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/2_Gray_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3_Beige_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/4_Olive_Green_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/5_Gold_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/6_Blue_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/7_Beige_Summer_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/8_Minky_Texture.jpg"]}',
	  'insert product description here',
		 'print_single', 169.99, 129.99, 0);
		 
INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Couples Family History Print',
 '{"tags":["blanket","printbinary","tree","family", "history", "genealogy", "custom", "branches","personal","couple","pair","married","spouse","grandkids","grandchildren","grandparents","children","parents"]}',
  'https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3Gen_Gray_Fall_Front.jpg',
	 '{"thumbnails":["https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3Gen_Gray_Fall_Back.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/1_Dark_Brown_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/2_Gray_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/3_Beige_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/4_Olive_Green_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/5_Gold_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/6_Blue_Fall_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/7_Beige_Summer_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/8_Minky_Texture.jpg"]}',
	  'insert product description here',
		 'print_binary', 169.99, 129.99, 0);

INSERT INTO products (product_name, product_tags, product_image, product_thumbs, product_desc, product_type, product_price, product_sale, product_shipping)
VALUES ('Grandparents, Kids and Grandkids Family History Print',
 '{"tags":["blanket","printinverted","tree","family", "history", "genealogy", "custom", "branches","personal","kids","progeny","grandkids","grandchildren","grandparents","children","parents"]}',
  'https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/GKG_Front_Photo.jpg',
	 '{"thumbnails":["https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/GKG_Back_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/1_Dark_Brown_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/2_Gray_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/3_Beige_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/4_Olive_Green_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/5_Gold_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/6_Blue_Fall_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_GKG/7_Beige_Summer_GKG_Photo.jpg","https://s3-us-west-1.amazonaws.com/parchmentgoods/product-images/blanket_family_history_3gen/8_Minky_Texture.jpg"]}',
	  'insert product description here',
		 'print_inverted', 169.99, 129.99, 0);
